name: CI
on: 

  workflow_dispatch:

  pull_request:
    branches:
      - master

jobs:
  DEV:    
    runs-on: macos-latest
    environment: DEV

    steps: 
      - uses: actions/checkout@v2
      
      - name: Run a script
        run: |
          echo "I am running a job in the DEV environment"
  
  PROD:    
    runs-on: macos-latest
    environment: PROD
    needs: DEV

    steps: 
      - uses: actions/checkout@v2
      
      - name: Run a script
        run: |
          echo "I am running a job in the PROD environment"