# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "feature/practice-advance" ]
  pull_request:
    branches: [ "feature/practice-advance" ]

jobs:
  DEV:    
    runs-on: macos-latest
    environment: DEV

    steps: 
      - uses: actions/checkout@v2
      
      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

        # Set up JDK to Java 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Install melos
      - name: Install Melos
        run: flutter pub global activate melos

      # Build the APK for the dev flavor
      - name: Build Android APK
        run: |
          cd practice-advance
          melos exec --scope=practice_advance -- flutter build apk --debug --flavor dev
      # Build the iOS app for the dev flavor
      - name: Build iOS IPA
        run: |
          cd practice-advance
          melos exec --scope=practice_advance -- flutter build ios --debug --flavor dev --no-codesign
  
  PROD:    
    runs-on: macos-latest
    environment: PROD
    needs: DEV

    steps: 
      - uses: actions/checkout@v2
      
      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

        # Set up JDK to Java 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Install melos
      - name: Install Melos
        run: flutter pub global activate melos

      # Build the APK for the prod flavor
      - name: Build Android APK
        run: |
          cd practice-advance
          melos exec --scope=practice_advance -- flutter build apk --debug --flavor prod
      # Build the iOS app for the prod flavor
      - name: Build iOS IPA
        run: |
          cd practice-advance
          melos exec --scope=practice_advance -- flutter build ios --debug --flavor prod --no-codesign
