name: practice_advance
description: "A new Flutter project."

# Remove this line if you wish to publish to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
  # Core Flutter SDK
    sdk: flutter  

  # Icons for iOS-style (Cupertino) widgets
  cupertino_icons: ^1.0.8  

  # Functional programming library, often used for handling Either and Option types
  dartz: ^0.10.1  

  # A powerful HTTP client for Dart, used for making network requests
  dio: ^5.7.0  

  # State management library using the Bloc pattern
  flutter_bloc: ^8.1.6  

  # Dependency injection (service locator) library
  get_it: ^7.7.0

  # Declarative routing for Flutter apps
  go_router: ^14.2.7  

  # Check internet connectivity status
  connectivity_plus: ^6.0.5  

  # Query management library for caching and fetching data
  fl_query: ^1.1.0

  # NoSQL database for local storage in Flutter apps  
  isar: ^3.1.0+1  

  # Access to commonly used locations on the filesystem (e.g., documents, temp)
  path_provider: ^2.1.4  

  # Helps in previewing apps on various devices and screen sizes
  device_preview: ^1.2.0  

  # Isar database engine specific for Flutter
  isar_flutter_libs: ^3.1.0+1  

  # Secure storage for sensitive data like tokens
  flutter_secure_storage: ^9.2.2  

  # Utilities for controlling event handling in Blocs to improve performance
  bloc_concurrency: ^0.2.5  

  # Efficiently load and cache network images
  cached_network_image: ^3.4.1  

  # Internationalization support (formatting dates, numbers, etc.)
  intl: ^0.19.0  

  # Load environment variables from a .env file
  flutter_dotenv: ^5.1.0    

  # Debugging and logging tool with advanced features
  talker: ^4.4.1  

  # Helps in responsive UI design by adapting layout based on screen size
  flutter_screenutil: ^5.9.3  

  # Load and display SVG (vector) images in Flutter
  flutter_svg: ^2.0.10+1  

  # Middleware for logging Dio network requests and responses via Talker
  talker_dio_logger: ^4.4.1  

  # Middleware for logging Bloc state changes and events via Talker
  talker_bloc_logger: ^4.4.1  

  # Talker extension for displaying logs and errors in a Flutter UI
  talker_flutter: ^4.4.1  

  # Local package for handling API calls in the monorepo setup
  api_client:
    path: ../../packages/api_client  

dev_dependencies:
  # Testing framework for Flutter apps
  flutter_test:
    sdk: flutter  

  # Linting rules to enforce best practices in Flutter
  flutter_lints: ^4.0.0  

  # Code generation tool used for generating code like serializers, Isar models, etc.
  build_runner: ^2.4.12  

  # Code generator for Isar database models
  isar_generator: ^3.0.0  

flutter:
  # Enables Material Design components in the app
  uses-material-design: true  

  assets:
  # Specifies the .env file for loading environment variables
  - .env  

