name: practice_advance_design
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1

  # Local package for handling API calls in the monorepo setup
  talker_package:
    path: ../../packages/talker_package
  go_router: ^14.2.7
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code generation tool used for generating code like serializers, Isar models, etc.
  build_runner: ^2.4.12  
  flutter_gen_runner: 5.3.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: ../practice_advance_design/assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: ../practice_advance_design/assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: ../practice_advance_design/assets/fonts/Roboto/Roboto-Bold.ttf          
    - family: OpenSans
      fonts:
        - asset: ../practice_advance_design/assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: ../practice_advance_design/assets/fonts/Roboto/Roboto-Regular.ttf

# Config gen assets
flutter_gen:
  output: lib/core/resources/assets_generated/ # Optional (default: lib/gen/)
  # Optional
  integrations:
    flutter_svg: true
  